version: '3.7'

services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl/certs/:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - star
    restart: always

  star:
    container_name: star
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5005:5000
